<?php
// database/seeders/TmWingSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TmWingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $wings = [
            [
                'id' => 1,
                'wing_name' => 'Barishal_W(A)',
                'wing_code' => 'Barishal_W(A)',
                'aemp_id' => 671,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 4,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:44:53',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 2,
                'wing_name' => 'Chattogram_W(A)',
                'wing_code' => 'Chattogram_W(A)',
                'aemp_id' => 3034,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 12825,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 3,
                'wing_name' => 'Cumilla_W(A)',
                'wing_code' => 'Cumilla_W(A)',
                'aemp_id' => 262,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 4,
                'wing_name' => 'Dhaka_East_W(A)',
                'wing_code' => 'Dhaka_East_W(A)',
                'aemp_id' => 67,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 5,
                'wing_name' => 'Dhaka_Metro_W(A)',
                'wing_code' => 'Dhaka_Metro_W(A)',
                'aemp_id' => 139,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 6,
                'wing_name' => 'Dhaka_West_W(A)',
                'wing_code' => 'Dhaka_West_W(A)',
                'aemp_id' => 363,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 2,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 7,
                'wing_name' => 'Khulna_W(A)',
                'wing_code' => 'Khulna_W(A)',
                'aemp_id' => 115,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:54',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 8,
                'wing_name' => 'Mymensing_W(A)',
                'wing_code' => 'Mymensing_W(A)',
                'aemp_id' => 77,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 9,
                'wing_name' => 'North_Bengal_W(A)',
                'wing_code' => 'North_Bengal_W(A)',
                'aemp_id' => 13015,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 10,
                'wing_name' => 'Sylhet_W(A)',
                'wing_code' => 'Sylhet_W(A)',
                'aemp_id' => 65,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => ' A ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 11,
                'wing_name' => 'Chattogram_W(B)',
                'wing_code' => 'Chattogram_W(B)',
                'aemp_id' => 43,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 12,
                'wing_name' => 'Cumilla_W(B)',
                'wing_code' => 'Cumilla_W(B)',
                'aemp_id' => 307,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 13,
                'wing_name' => 'Dhaka_East_W(B)',
                'wing_code' => 'Dhaka_East_W(B)',
                'aemp_id' => 578,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-23 11:49:57',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 578,
                'attr4' => 0
            ],
            [
                'id' => 14,
                'wing_name' => 'Dhaka_Central_W(B)',
                'wing_code' => 'Dhaka_Central_W(B)',
                'aemp_id' => 568,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 885,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-07-16 16:48:36',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 15,
                'wing_name' => 'Mymensing_W(B)',
                'wing_code' => 'Mymensing_W(B)',
                'aemp_id' => 287,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 14,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-02-03 10:56:50',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 16,
                'wing_name' => 'North_Bengal_W(B)',
                'wing_code' => 'North_Bengal_W(B)',
                'aemp_id' => 580,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 17,
                'wing_name' => 'Barishal_W(B)',
                'wing_code' => 'Barishal_W(B)',
                'aemp_id' => 569,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 14,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-02-03 10:57:38',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 18,
                'wing_name' => 'Sylhet_W(B)',
                'wing_code' => 'Sylhet_W(B)',
                'aemp_id' => 119,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' B ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 19,
                'wing_name' => 'Chattogram_W(C)',
                'wing_code' => 'Chattogram_W(C)',
                'aemp_id' => 151,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 20,
                'wing_name' => 'Cumilla_W(C)',
                'wing_code' => 'Cumilla_W(C)',
                'aemp_id' => 130,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 21,
                'wing_name' => 'Dhaka_East_W(C)',
                'wing_code' => 'Dhaka_East_W(C)',
                'aemp_id' => 330,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 22,
                'wing_name' => 'Dhaka_West_W(C)',
                'wing_code' => 'Dhaka_West_W(C)',
                'aemp_id' => 214,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 23,
                'wing_name' => 'Mymensing_W(C)',
                'wing_code' => 'Mymensing_W(C)',
                'aemp_id' => 150,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 24,
                'wing_name' => 'North_Bengal_W(C)',
                'wing_code' => 'North_Bengal_W(C)',
                'aemp_id' => 172,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 25,
                'wing_name' => 'South_Bengal_W(C)',
                'wing_code' => 'South_Bengal_W(C)',
                'aemp_id' => 342,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 26,
                'wing_name' => 'Sylhet_W(C)',
                'wing_code' => 'Sylhet_W(C)',
                'aemp_id' => 428,
                'slgp_id' => 3,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 4,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:56',
                'var' => 1,
                'attr1' => ' C ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 27,
                'wing_name' => 'Chattogram_W(F)',
                'wing_code' => 'Chattogram_W(F)',
                'aemp_id' => 1842,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 28,
                'wing_name' => 'Cumilla_W(F)',
                'wing_code' => 'Cumilla_W(F)',
                'aemp_id' => 550,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 29,
                'wing_name' => 'Dhaka_East_W(F)',
                'wing_code' => 'Dhaka_East_W(F)',
                'aemp_id' => 1014,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 30,
                'wing_name' => 'Dhaka_West_W(F)',
                'wing_code' => 'Dhaka_West_W(F)',
                'aemp_id' => 2374,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 31,
                'wing_name' => 'Mymensing_W(F)',
                'wing_code' => 'Mymensing_W(F)',
                'aemp_id' => 1651,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 32,
                'wing_name' => 'North_Bengal_W(F)',
                'wing_code' => 'North_Bengal_W(F)',
                'aemp_id' => 1023,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 754,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2023-02-21 09:36:49',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 33,
                'wing_name' => 'Jashore_W(F)',
                'wing_code' => 'Jashore_W(F)',
                'aemp_id' => 35617,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 31062,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-01-21 18:28:03',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 34,
                'wing_name' => 'Sylhet_W(F)',
                'wing_code' => 'Sylhet_W(F)',
                'aemp_id' => 5114,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 4,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2022-02-08 12:48:57',
                'var' => 1,
                'attr1' => ' F ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 35,
                'wing_name' => 'Chattogram_W(G)',
                'wing_code' => 'Chattogram_W(G)',
                'aemp_id' => 51593,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 777,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-05-02 18:12:30',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 36,
                'wing_name' => 'Cumilla_W(G)',
                'wing_code' => 'Cumilla_W(G)',
                'aemp_id' => 0,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2021-10-30 18:33:42',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 37,
                'wing_name' => 'Dhaka-1_W(G)',
                'wing_code' => 'Dhaka-1_W(G)',
                'aemp_id' => 17314,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 777,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-05-02 12:01:34',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 38,
                'wing_name' => 'Dhaka-2_W(G)',
                'wing_code' => 'Dhaka-2_W(G)',
                'aemp_id' => 33454,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 777,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-05-02 12:02:21',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 39,
                'wing_name' => 'Mymensing_W(G)',
                'wing_code' => 'Mymensing_W(G)',
                'aemp_id' => 0,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 2,
                'aemp_iusr' => 1,
                'aemp_eusr' => 885,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2025-09-13 13:55:37',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 40,
                'wing_name' => 'Bogura_W(G)',
                'wing_code' => 'Bogura_W(G)',
                'aemp_id' => 34122,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 885,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2025-09-13 13:33:37',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 41,
                'wing_name' => 'Khulna_W(G)',
                'wing_code' => 'Khulna_W(G)',
                'aemp_id' => 35307,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 12856,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-01-25 11:16:09',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 42,
                'wing_name' => 'Sylhet_W(G)',
                'wing_code' => 'Sylhet_W(G)',
                'aemp_id' => 51595,
                'slgp_id' => 5,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 777,
                'created_at' => '2022-02-08 12:44:53',
                'updated_at' => '2026-05-02 18:12:06',
                'var' => 1,
                'attr1' => ' G ',
                'attr2' => '',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 43,
                'wing_name' => 'Khulna_W(B)',
                'wing_code' => 'Khulna_W(B)',
                'aemp_id' => 536,
                'slgp_id' => 2,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 1,
                'aemp_eusr' => 1,
                'created_at' => '2021-08-17 14:12:58',
                'updated_at' => '2022-02-08 12:48:55',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 44,
                'wing_name' => 'Barishal_W(A)_1',
                'wing_code' => 'Barishal_W(A)_1',
                'aemp_id' => 671,
                'slgp_id' => 1,
                'cont_id' => 1,
                'lfcl_id' => 2,
                'aemp_iusr' => 724,
                'aemp_eusr' => 885,
                'created_at' => '2021-09-20 10:20:26',
                'updated_at' => '2024-08-24 12:13:27',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 45,
                'wing_name' => 'Cumilla_W(K)',
                'wing_code' => 'Cumilla_W(K)',
                'aemp_id' => 0,
                'slgp_id' => 6,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 724,
                'aemp_eusr' => 724,
                'created_at' => '2021-09-20 10:47:28',
                'updated_at' => '2021-09-20 10:47:28',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 46,
                'wing_name' => 'Dhaka_West_W(K)',
                'wing_code' => 'Dhaka_West_W(K)',
                'aemp_id' => 0,
                'slgp_id' => 6,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 724,
                'aemp_eusr' => 724,
                'created_at' => '2021-09-20 10:47:52',
                'updated_at' => '2021-09-20 10:47:52',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 47,
                'wing_name' => 'Dhaka_East_W(K)',
                'wing_code' => 'Dhaka_East_W(K)',
                'aemp_id' => 0,
                'slgp_id' => 6,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 724,
                'aemp_eusr' => 724,
                'created_at' => '2021-09-20 10:48:29',
                'updated_at' => '2021-09-20 10:48:29',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 48,
                'wing_name' => 'Mymensing_W(K)',
                'wing_code' => 'Mymensing_W(K)',
                'aemp_id' => 0,
                'slgp_id' => 6,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 724,
                'aemp_eusr' => 724,
                'created_at' => '2021-09-20 10:48:59',
                'updated_at' => '2021-09-20 10:48:59',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 49,
                'wing_name' => 'Chattogram_W(D)',
                'wing_code' => 'Chattogram_W(D)',
                'aemp_id' => 23117,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 09:53:48',
                'updated_at' => '2023-12-18 15:30:58',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 50,
                'wing_name' => 'Cumilla_W(D)',
                'wing_code' => 'Cumilla_W(D)',
                'aemp_id' => 23120,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 09:59:23',
                'updated_at' => '2023-12-18 15:31:11',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 51,
                'wing_name' => 'Dhaka_East_W(D)',
                'wing_code' => 'Dhaka_East_W(D)',
                'aemp_id' => 23116,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 10:02:19',
                'updated_at' => '2023-12-18 15:31:28',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 52,
                'wing_name' => 'Dhaka_West_W(D)',
                'wing_code' => 'Dhaka_West_W(D)',
                'aemp_id' => 52205,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 777,
                'created_at' => '2023-12-18 10:06:00',
                'updated_at' => '2026-07-08 16:26:03',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 53,
                'wing_name' => 'Mymensing_W(D)',
                'wing_code' => 'Mymensing_W(D)',
                'aemp_id' => 23115,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 777,
                'created_at' => '2023-12-18 10:07:26',
                'updated_at' => '2024-11-16 11:45:10',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 54,
                'wing_name' => 'North_Bengal_W(D)',
                'wing_code' => 'North_Bengal_W(D)',
                'aemp_id' => 23122,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 11:26:45',
                'updated_at' => '2023-12-18 15:31:59',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 55,
                'wing_name' => 'South_Bengal_W(D)',
                'wing_code' => 'South_Bengal_W(D)',
                'aemp_id' => 23119,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 11:27:37',
                'updated_at' => '2023-12-18 15:32:14',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 56,
                'wing_name' => 'Sylhet_W(D)',
                'wing_code' => 'Sylhet_W(D)',
                'aemp_id' => 23115,
                'slgp_id' => 9,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 885,
                'created_at' => '2023-12-18 11:28:55',
                'updated_at' => '2023-12-18 15:38:07',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 57,
                'wing_name' => 'Dhaka_Metro_W(CORP)',
                'wing_code' => 'Dhaka_Metro_W(CORP)',
                'aemp_id' => 24060,
                'slgp_id' => 8,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-01-06 11:24:32',
                'updated_at' => '2024-01-06 14:52:20',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 76,
                'wing_name' => 'Dhaka_W(CORP)',
                'wing_code' => 'Dhaka_W(CORP)',
                'aemp_id' => 2,
                'slgp_id' => 8,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 12:51:12',
                'updated_at' => '2024-10-21 12:51:12',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 77,
                'wing_name' => 'Sylhet_W(CORP)',
                'wing_code' => 'Sylhet_W(CORP)',
                'aemp_id' => 2,
                'slgp_id' => 8,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 12:51:38',
                'updated_at' => '2024-10-21 12:51:38',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 78,
                'wing_name' => 'Rajshahi_W(CORP)',
                'wing_code' => 'Rajshahi_W(CORP)',
                'aemp_id' => 2,
                'slgp_id' => 8,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 12:52:00',
                'updated_at' => '2024-10-21 12:52:00',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 79,
                'wing_name' => 'Dhaka_South_W(R)',
                'wing_code' => 'Dhaka_South_W(R)',
                'aemp_id' => 2,
                'slgp_id' => 10,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 14:19:41',
                'updated_at' => '2024-10-21 14:19:41',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 80,
                'wing_name' => 'Sylhet_Ctg_W(R)',
                'wing_code' => 'Sylhet_Ctg_W(R)',
                'aemp_id' => 2,
                'slgp_id' => 10,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 14:20:31',
                'updated_at' => '2024-10-21 14:20:31',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 81,
                'wing_name' => 'National_W(R)',
                'wing_code' => 'National_W(R)',
                'aemp_id' => 2,
                'slgp_id' => 10,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 2,
                'aemp_eusr' => 2,
                'created_at' => '2024-10-21 14:46:53',
                'updated_at' => '2024-10-21 14:46:53',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 82,
                'wing_name' => 'Dhaka_East_W(U)',
                'wing_code' => 'Dhaka_East_W(U)',
                'aemp_id' => 35140,
                'slgp_id' => 11,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 14,
                'aemp_eusr' => 14,
                'created_at' => '2025-12-22 16:37:22',
                'updated_at' => '2025-12-22 16:37:22',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 83,
                'wing_name' => 'Mymensing_W(U)',
                'wing_code' => 'Mymensing_W(U)',
                'aemp_id' => 35140,
                'slgp_id' => 11,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 14,
                'aemp_eusr' => 14,
                'created_at' => '2025-12-22 16:38:16',
                'updated_at' => '2025-12-22 16:38:16',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 84,
                'wing_name' => 'Sylhet_W(U)',
                'wing_code' => 'Sylhet_W(U)',
                'aemp_id' => 50016,
                'slgp_id' => 11,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 14,
                'aemp_eusr' => 777,
                'created_at' => '2025-12-22 16:38:56',
                'updated_at' => '2026-01-04 14:28:37',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 85,
                'wing_name' => 'Cumilla_W(U)',
                'wing_code' => 'Cumilla_W(U)',
                'aemp_id' => 23120,
                'slgp_id' => 11,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 777,
                'aemp_eusr' => 777,
                'created_at' => '2026-01-04 11:16:38',
                'updated_at' => '2026-01-04 11:16:38',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 86,
                'wing_name' => 'Chattogram_W(U)',
                'wing_code' => 'Chattogram_W(U)',
                'aemp_id' => 50010,
                'slgp_id' => 11,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 16,
                'aemp_eusr' => 777,
                'created_at' => '2026-01-04 11:19:43',
                'updated_at' => '2026-04-21 15:52:04',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ],
            [
                'id' => 200,
                'wing_name' => 'Barishal_W(F)',
                'wing_code' => 'Barishal_W(F)',
                'aemp_id' => 251,
                'slgp_id' => 4,
                'cont_id' => 1,
                'lfcl_id' => 1,
                'aemp_iusr' => 31062,
                'aemp_eusr' => 15990,
                'created_at' => '2026-01-21 18:22:14',
                'updated_at' => '2026-02-14 16:21:08',
                'var' => 1,
                'attr1' => '-',
                'attr2' => '-',
                'attr3' => 0,
                'attr4' => 0
            ]
        ];

        // Sort wings by ID in ascending order
        usort($wings, function($a, $b) {
            return $a['id'] - $b['id'];
        });

        // Insert data
        DB::table('tm_wing')->insert($wings);
    }
}
