SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO tm_wing VALUES('Barishal_W(A)', 'Barishal_W(A)', 'Barishalwinga');
INSERT INTO tm_wing VALUES('Chattogram_W(A)', 'Chattogram_W(A)', '023292');
INSERT INTO tm_wing VALUES('Cumilla_W(A)', 'Cumilla_W(A)', '174667');
INSERT INTO tm_wing VALUES('Dhaka_East_W(A)', 'Dhaka_East_W(A)', '118069');
INSERT INTO tm_wing VALUES('Dhaka_Metro_W(A)', 'Dhaka_Metro_W(A)', 'A118069');
INSERT INTO tm_wing VALUES('Dhaka_West_W(A)', 'Dhaka_West_W(A)', '173140');
INSERT INTO tm_wing VALUES('Khulna_W(A)', 'Khulna_W(A)', '01713431494');
INSERT INTO tm_wing VALUES('Mymensing_W(A)', 'Mymensing_W(A)', '114439');
INSERT INTO tm_wing VALUES('North_Bengal_W(A)', 'North_Bengal_W(A)', '000590');
INSERT INTO tm_wing VALUES('Sylhet_W(A)', 'Sylhet_W(A)', '017130');
INSERT INTO tm_wing VALUES('Chattogram_W(B)', 'Chattogram_W(B)', '000725');
INSERT INTO tm_wing VALUES('Cumilla_W(B)', 'Cumilla_W(B)', '003404');
INSERT INTO tm_wing VALUES('Dhaka_East_W(B)', 'Dhaka_East_W(B)', '147339');
INSERT INTO tm_wing VALUES('Dhaka_Central_W(B)', 'Dhaka_Central_W(B)', '158647');
INSERT INTO tm_wing VALUES('Mymensing_W(B)', 'Mymensing_W(B)', '005231');
INSERT INTO tm_wing VALUES('North_Bengal_W(B)', 'North_Bengal_W(B)', '009910');
INSERT INTO tm_wing VALUES('Barishal_W(B)', 'Barishal_W(B)', '003345');
INSERT INTO tm_wing VALUES('Sylhet_W(B)', 'Sylhet_W(B)', '004901');
INSERT INTO tm_wing VALUES('Chattogram_W(C)', 'Chattogram_W(C)', '178459');
INSERT INTO tm_wing VALUES('Cumilla_W(C)', 'Cumilla_W(C)', '003525');
INSERT INTO tm_wing VALUES('Dhaka_East_W(C)', 'Dhaka_East_W(C)', '01755540510');
INSERT INTO tm_wing VALUES('Dhaka_West_W(C)', 'Dhaka_West_W(C)', '01755537295');
INSERT INTO tm_wing VALUES('Mymensing_W(C)', 'Mymensing_W(C)', '002358');
INSERT INTO tm_wing VALUES('North_Bengal_W(C)', 'North_Bengal_W(C)', '116620');
INSERT INTO tm_wing VALUES('South_Bengal_W(C)', 'South_Bengal_W(C)', '178455');
INSERT INTO tm_wing VALUES('Sylhet_W(C)', 'Sylhet_W(C)', '172051');
INSERT INTO tm_wing VALUES('Chattogram_W(F)', 'Chattogram_W(F)', '026652');
INSERT INTO tm_wing VALUES('Cumilla_W(F)', 'Cumilla_W(F)', '165823');
INSERT INTO tm_wing VALUES('Dhaka_East_W(F)', 'Dhaka_East_W(F)', '111111');
INSERT INTO tm_wing VALUES('Dhaka_West_W(F)', 'Dhaka_West_W(F)', '444444');
INSERT INTO tm_wing VALUES('Mymensing_W(F)', 'Mymensing_W(F)', '136037');
INSERT INTO tm_wing VALUES('North_Bengal_W(F)', 'North_Bengal_W(F)', '166652');
INSERT INTO tm_wing VALUES('Jashore_W(F)', 'Jashore_W(F)', '165825');
INSERT INTO tm_wing VALUES('Sylhet_W(F)', 'Sylhet_W(F)', '026943');
INSERT INTO tm_wing VALUES('Chattogram_W(G)', 'Chattogram_W(G)', '176172');
INSERT INTO tm_wing VALUES('Dhaka-1_W(G)', 'Dhaka-1_W(G)', '164309');
INSERT INTO tm_wing VALUES('Dhaka-2_W(G)', 'Dhaka-2_W(G)', '176173');
INSERT INTO tm_wing VALUES('Bogura_W(G)', 'Bogura_W(G)', '075155');
INSERT INTO tm_wing VALUES('Khulna_W(G)', 'Khulna_W(G)', '175763');
INSERT INTO tm_wing VALUES('Sylhet_W(G)', 'Sylhet_W(G)', '176170');
INSERT INTO tm_wing VALUES('Khulna_W(B)', 'Khulna_W(B)', '002078');
INSERT INTO tm_wing VALUES('Barishal_W(A)_1', 'Barishal_W(A)_1', 'Barishalwinga');
INSERT INTO tm_wing VALUES('Chattogram_W(D)', 'Chattogram_W(D)', '115216');
INSERT INTO tm_wing VALUES('Cumilla_W(D)', 'Cumilla_W(D)', '114685');
INSERT INTO tm_wing VALUES('Dhaka_East_W(D)', 'Dhaka_East_W(D)', '114457');
INSERT INTO tm_wing VALUES('Dhaka_West_W(D)', 'Dhaka_West_W(D)', 'D116317');
INSERT INTO tm_wing VALUES('Mymensing_W(D)', 'Mymensing_W(D)', '114459');
INSERT INTO tm_wing VALUES('North_Bengal_W(D)', 'North_Bengal_W(D)', '115203');
INSERT INTO tm_wing VALUES('South_Bengal_W(D)', 'South_Bengal_W(D)', '114705');
INSERT INTO tm_wing VALUES('Sylhet_W(D)', 'Sylhet_W(D)', '114459');
INSERT INTO tm_wing VALUES('Dhaka_Metro_W(CORP)', 'Dhaka_Metro_W(CORP)', '008771');
INSERT INTO tm_wing VALUES('Dhaka_W(CORP)', 'Dhaka_W(CORP)', '987654');
INSERT INTO tm_wing VALUES('Sylhet_W(CORP)', 'Sylhet_W(CORP)', '987654');
INSERT INTO tm_wing VALUES('Rajshahi_W(CORP)', 'Rajshahi_W(CORP)', '987654');
INSERT INTO tm_wing VALUES('Dhaka_South_W(R)', 'Dhaka_South_W(R)', '987654');
INSERT INTO tm_wing VALUES('Sylhet_Ctg_W(R)', 'Sylhet_Ctg_W(R)', '987654');
INSERT INTO tm_wing VALUES('National_W(R)', 'National_W(R)', '987654');
INSERT INTO tm_wing VALUES('Dhaka_East_W(U)', 'Dhaka_East_W(U)', '164469');
INSERT INTO tm_wing VALUES('Mymensing_W(U)', 'Mymensing_W(U)', '164469');
INSERT INTO tm_wing VALUES('Sylhet_W(U)', 'Sylhet_W(U)', '173022');
INSERT INTO tm_wing VALUES('Cumilla_W(U)', 'Cumilla_W(U)', '114685');
INSERT INTO tm_wing VALUES('Chattogram_W(U)', 'Chattogram_W(U)', '175004');
INSERT INTO tm_wing VALUES('Barishal_W(F)', 'Barishal_W(F)', '173210');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
