<?php

return [
    'mode'                  => env('DOMPDF_MODE', 'utf-8'),
    'defines'               => [
        'DOMPDF_FONT_DIR'   => storage_path('fonts/'),
        'DOMPDF_FONT_CACHE' => storage_path('fonts/'),
        'DOMPDF_TEMP_DIR'   => sys_get_temp_dir(),
        'DOMPDF_CHROOT'     => public_path(),
        'DOMPDF_ENABLE_CSS_FLOAT' => true,
        'DOMPDF_ENABLE_JAVASCRIPT' => false,
        'DOMPDF_PDF_STANDARD' => 'PDF/A-1b',
        'DOMPDF_DEFAULT_MEDIA_TYPE' => 'screen',
        'DOMPDF_DEFAULT_PAPER_SIZE' => 'a4',
        'DOMPDF_DPI' => 150,
        'DOMPDF_ENABLE_REMOTE' => true,
        'DOMPDF_ADMIN_USERNAME' => env('DOMPDF_ADMIN_USERNAME', 'admin'),
        'DOMPDF_ADMIN_PASSWORD' => env('DOMPDF_ADMIN_PASSWORD', 'password'),
    ],
    'font_path'             => storage_path('fonts/'),
    'font_cache'            => storage_path('fonts/'),
    'temp_dir'              => sys_get_temp_dir(),
    'chroot'                => public_path(),
    'logOutputFile'         => storage_path('logs/dompdf.log'),
    'defaultMediaType'      => env('DOMPDF_DEFAULT_MEDIA_TYPE', 'screen'),
    'defaultPaperSize'      => env('DOMPDF_DEFAULT_PAPER_SIZE', 'a4'),
    'margin_top'            => 0,
    'margin_right'          => 0,
    'margin_bottom'         => 0,
    'margin_left'           => 0,
    'isPhpEnabled'          => false,
    'isRemoteEnabled'       => true,
    'isJavascriptEnabled'   => false,
    'isHtml5ParserEnabled'  => true,
    'isFontSubsettingEnabled' => false,
    'debugPng'              => false,
    'debugKeepTemp'         => false,
    'debugCss'              => false,
    'debugLayout'           => false,
    'debugLayoutLines'      => true,
    'debugLayoutBlocks'     => true,
    'debugLayoutInline'     => true,
    'debugLayoutPaddingBox' => true,
    'pdfBackend'            => env('DOMPDF_PDF_BACKEND', 'CPDF'),
    'pdflibLicense'         => env('DOMPDF_PDFLIB_LICENSE', ''),

    'custom_font_dir'       => base_path('resources/fonts/'),
    'custom_font_data'      => [
        'kalpurush' => [
            'normal' => base_path('resources/fonts/kalpurush.ttf'),
            'bold'   => base_path('resources/fonts/kalpurush.ttf'),
        ],
    ],
];
